wip 2

diff --git a/docker-compose.test.yml b/docker-compose.test.yml
--- a/docker-compose.test.yml
+++ b/docker-compose.test.yml
@@ -24,9 +24,19 @@ services:
       createdb --host=testdb --username=postgres cmsdbfortesting ;
       cmsInitDB ;
       sudo chown cmsuser:cmsuser ./codecov ;
-      pytest --cov . --cov-report xml:codecov/unittests.xml ;
+      UNIT=$(pytest --cov . --cov-report xml:codecov/unittests.xml) ;
       dropdb --host=testdb --username=postgres cmsdbfortesting ;
       createdb --host=testdb --username=postgres cmsdbfortesting ;
       cmsInitDB ;
-      cmsRunFunctionalTests -v --coverage codecov/functionaltests.xml ;
+      FUNC=$(cmsRunFunctionalTests -v --coverage codecov/functionaltests.xml) ;
+
+      # This contraption is needed because otherwise failing unit tests aren't
+      # reported in the CI as long as the functional tests are passing. Ideally
+      # we should get rid of `cmsRunFunctionalTests` and make those tests work
+      # with pytest so they can be auto-discovered and run with it.
+      if [ $UNIT -ne 0 ] || [ $FUNC -ne 0 ]; then
+        exit 1
+      else
+        exit 0
+      fi
       "
